In [3]:
#Array Manipulation refers to transforming the shape and dimensions of an array
import numpy as np

# ARRAY MANIPULATION METHODS

Method 1: .RESHAPE()

In [5]:
np.linspace(2,8, ) 

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [6]:
np.linspace(2,8, ) .shape

(50,)

In [7]:
#To change the shape ie to reshape the array, the reshape function will take 2 arguments:(rows,column)
np.linspace(2,8).reshape(2,25)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
        2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
        3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
        3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
        4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
       [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
        5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
        6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
        6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
        7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [8]:
#When reshaping an array, the dimensions of the new shape must be both factors that multiply to give the original shape
#The product of the dimension of the new shape should give the original shape
#example to reshape the above array of shape 50,you can reshape to (5,10),(2,25),(1,50),(10,5),(25,2)
np.linspace(2,8).reshape(5,10)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
        2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082],
       [3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
        3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061],
       [4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
        5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041],
       [5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
        6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ],
       [6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
        7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [9]:
np.linspace(2,8).reshape(10,5)

array([[2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592],
       [2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082],
       [3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571],
       [3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061],
       [4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551],
       [5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041],
       [5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531],
       [6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ],
       [6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ],
       [7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ]])

In [10]:
np.linspace(2,8).reshape(2,10)

ValueError: cannot reshape array of size 50 into shape (2,10)

In [12]:
#Using Arange
np.arange(1,37)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [13]:
np.arange(1,37) .shape

(36,)

In [14]:
#The above arrage can be reshaped with 
np.arange(1,37) .reshape(3,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [15]:
np.arange(1,37) .reshape(12,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [16]:
np.arange(1,37) .reshape(4,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

In [17]:
np.arange(1,37) .reshape(9,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [18]:
np.arange(1,37) .reshape(6,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [19]:
np.arange(1,37) .reshape(18,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36]])

METHOD 2: TRANSPOSE

In [20]:
#In python, chaining is the process of taking the result of an array and applying another method or operation to it using .
#The transpose method converts the rows to columns and vice versa
np.transpose(np.arange(1,37) .reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [21]:
np.transpose(np.arange(1,37) .reshape(9,4))
#the transpose has converted the rows to columns and the columns to rows, we now have(4 rows,9 columns)

array([[ 1,  5,  9, 13, 17, 21, 25, 29, 33],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

METHOD 3:STACKING

In [22]:
#We have the horizontal(H-Stacking) and the Vertical(V-Stacking). 
#Stacking is a way of adding up arrays on top of themselves, example
a=np.array([1,2,3])
b=np.array([[9,6,8],[9,1,6]])

In [23]:
a

array([1, 2, 3])

In [35]:
a.ndim

1

In [24]:
b

array([[9, 6, 8],
       [9, 1, 6]])

In [36]:
b.ndim

2

In [30]:
#To stack a and b horizontally
np.hstack([a,b])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [37]:
#The error for hstack occured because a and b do not have the same dimension
#To be able to perform stacking, the arrays involved must be of the same dimension
#For hstacking, the arrays to be stacked must have the same number of rows
#For vstacking, the arrays to be stacked must have the same number of columns

array([1, 2, 3])

In [38]:
b

array([[9, 6, 8],
       [9, 1, 6]])

In [32]:
np.vstack([a,b])

array([[1, 2, 3],
       [9, 6, 8],
       [9, 1, 6]])

In [42]:
#Introducing a third array c
c=np.array([[9,0,12],[76,9,21]])

In [43]:
c

array([[ 9,  0, 12],
       [76,  9, 21]])

In [44]:
np.hstack([c,b])

array([[ 9,  0, 12,  9,  6,  8],
       [76,  9, 21,  9,  1,  6]])

In [46]:
np.hstack([b,c])

array([[ 9,  6,  8,  9,  0, 12],
       [ 9,  1,  6, 76,  9, 21]])

In [47]:
np.vstack([a,b,c])

array([[ 1,  2,  3],
       [ 9,  6,  8],
       [ 9,  1,  6],
       [ 9,  0, 12],
       [76,  9, 21]])

# MATHEMATICAL OPERATIONS IN NUMPY

In [48]:
a

array([1, 2, 3])

In [49]:
b

array([[9, 6, 8],
       [9, 1, 6]])

In [50]:
c

array([[ 9,  0, 12],
       [76,  9, 21]])

MULTIPLICATION

In [51]:
a*b

array([[ 9, 12, 24],
       [ 9,  2, 18]])

In [52]:
c*b

array([[ 81,   0,  96],
       [684,   9, 126]])

SUBTRACTION

In [4]:
#Introducing some new arrays
o=np.array([2,3,4])
w=np.array([3,4,5])

AGGREGATE FUNCTIONS

In [5]:
#Aggregate functions have to do with a particular array

1. Sum Aggregate Function

In [6]:
o.sum()   #sums up everything in the o array

9

In [7]:
w.sum()

12

In [60]:
np.arange(1,37) .reshape(6,6).sum()

666

In [64]:
#recalling the array below then using chaining
np.transpose(np.arange(1,37) .reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [66]:
np.transpose(np.arange(1,37) .reshape(6,6)).sum(axis=0)                         #sum of axis=0 adds up all items in each column

array([ 21,  57,  93, 129, 165, 201])

In [67]:
np.transpose(np.arange(1,37) .reshape(6,6)).sum(axis=1)                         #sum of axis=1 adds up all items in each row

array([ 96, 102, 108, 114, 120, 126])

2. Min Aggregate Function

In [69]:
#Min returns the lowest value in the array
np.transpose(np.arange(1,37) .reshape(6,6)) .min()

1

In [73]:
np.transpose(np.arange(1,37) .reshape(6,6)) .min(axis=0)                             #returns the lowest value in each column

array([ 1,  7, 13, 19, 25, 31])

In [71]:
np.transpose(np.arange(1,37) .reshape(6,6)) .min(axis=1)                            #returns the lovest value in each row

array([1, 2, 3, 4, 5, 6])

3. Max Aggregate Function

In [72]:
#Max returns the highest value in the array
np.transpose(np.arange(1,37) .reshape(6,6)) .max()

36

In [74]:
np.transpose(np.arange(1,37) .reshape(6,6)) .max(axis=0)                             #returns the highest value in each column

array([ 6, 12, 18, 24, 30, 36])

In [75]:
np.transpose(np.arange(1,37) .reshape(6,6)) .max(axis=1)                               #returns the highest value in each row

array([31, 32, 33, 34, 35, 36])

4. Cummulative Sum Aggregate

In [76]:
#Cummulative sum adds each element of the array and returns the result progressively
np.transpose(np.arange(1,37) .reshape(6,6))

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [78]:
np.transpose(np.arange(1,37) .reshape(6,6)) .cumsum(axis=0)                #returns the cummulative sum of items in each column

array([[  1,   7,  13,  19,  25,  31],
       [  3,  15,  27,  39,  51,  63],
       [  6,  24,  42,  60,  78,  96],
       [ 10,  34,  58,  82, 106, 130],
       [ 15,  45,  75, 105, 135, 165],
       [ 21,  57,  93, 129, 165, 201]])

In [79]:
np.transpose(np.arange(1,37) .reshape(6,6)) .cumsum(axis=1)              #returns the cummulative sum of items in each row

array([[  1,   8,  21,  40,  65,  96],
       [  2,  10,  24,  44,  70, 102],
       [  3,  12,  27,  48,  75, 108],
       [  4,  14,  30,  52,  80, 114],
       [  5,  16,  33,  56,  85, 120],
       [  6,  18,  36,  60,  90, 126]])

5. Mean Aggregate

In [81]:
#Mean returns the average ie sum/total no of samples
np.transpose(np.arange(1,37) .reshape(6,6)) .cumsum(axis=1) .mean(axis=0)  

array([  3.5,  13. ,  28.5,  50. ,  77.5, 111. ])

In [82]:
np.transpose(np.arange(1,37) .reshape(6,6)) .cumsum(axis=1) .mean(axis=1)

array([38.5, 42. , 45.5, 49. , 52.5, 56. ])

In [83]:
np.transpose(np.arange(1,37) .reshape(6,6)) .cumsum(axis=1) .mean()

47.25

6. Median Aggregate

In [84]:
#Median returns the middle value/number after arranging the items in ascending or descending order
#Here, we insert every item inside the median function
np.median(np.transpose(np.arange(1,37)))

18.5

7. Standard Deviation

In [87]:
np.transpose(np.arange(1,37)) .std()

10.388294694831615

8. Sin,Cos,Tan

In [89]:
np.sin(np.transpose(np.arange(1,37)))

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162,
       -0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
       -0.99177885])

In [90]:
np.cos(np.transpose(np.arange(1,37)))

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145,
        0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
       -0.12796369])

In [91]:
np.tan(np.transpose(np.arange(1,37)))

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
       -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,  7.75047091e+00])

In [92]:
#Most mathematical operations can be carried out in Numpy