In [2]:
#Numpy is an acronym for numerical python. We need to install and import numpy before using


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np   #tells the computer you want to use numpy which we can shorten to np for ease of coding

# ARRAYS

In [ ]:
#Arrays are lists, collections of informations. 
#The list data structure has close similarities with numpy hence most arrays will be created using a list data structure

                            #Creating our first array

In [ ]:
#We can create an array by first creating a list and then converting it to an array

In [5]:
#We create a list named d
d = [1,3,5,2,8,23]

In [6]:
type(d)

list

In [7]:
#To convert this list to an array,
np.array(d)

array([ 1,  3,  5,  2,  8, 23])

In [8]:
#To confirm that the list has been converted to an array, we can assign the array to a variable s and check the type
s=np.array(d)

In [9]:
type(s)

numpy.ndarray

In [27]:
#The above response means that s is a numpy n-dimensional array, meaning you can create multidimensional arrays with numpy.
#To verify the datatype of the above array as an integer, the syntax is arrayname.dtype
s.dtype

dtype('int32')

In [13]:
#We can investigate the structure and form of our arrays by
s.ndim     #This is asking what is the dimension of our array,in this case, our array is one-dimensional

1

In [15]:
#To investigate the shape of our array,shape returns the total no of rows and columns ie (row,column)
#In this case we have 6 rows and 1 column
s.shape  #the 6 means that there are 6 items inside the s array

(6,)

In [16]:
#To investigate the size of the array,this will return the product of the no of rows and no of columns ie x and y dimensions
#In this case, the size of array s will be 6 * 1= 6
s.size

6

                                     #Creating Multidimensional Arrays

In [17]:
#We create a list of list. 
c=[[2,3,4,5,1,2,3],[5,4,5,6,7,4,3],[5,3,5,7,3,9,4]]

In [18]:
c

[[2, 3, 4, 5, 1, 2, 3], [5, 4, 5, 6, 7, 4, 3], [5, 3, 5, 7, 3, 9, 4]]

In [20]:
#convert c from a python list to a numpy array
np.array(c)     #This will give us a stack of arrays

array([[2, 3, 4, 5, 1, 2, 3],
       [5, 4, 5, 6, 7, 4, 3],
       [5, 3, 5, 7, 3, 9, 4]])

In [21]:
#To be able to create a numpy multidimensional array, each array must contain THE SAME number of items
#Assign this array to a new variable u
u=np.array(c)

In [22]:
u

array([[2, 3, 4, 5, 1, 2, 3],
       [5, 4, 5, 6, 7, 4, 3],
       [5, 3, 5, 7, 3, 9, 4]])

In [23]:
u.ndim   #the u array has 2 dimensions:the x and y components

2

In [24]:
u.shape  #the u array has 3 rows and 7 columns. The row information usually comes before the column info ie(row,column)

(3, 7)

In [25]:
u.size

21

In [26]:
#When creating an array, if you don't specify a datatype, numpy automatically tries to assign a datatype of choice to the array.
u.dtype

dtype('int32')

In [28]:
#To change the datatype of the above array u, call the array u=np.array(c) and assign it a data type

In [29]:
u=np.array(c, dtype=np.int16)

In [30]:
u

array([[2, 3, 4, 5, 1, 2, 3],
       [5, 4, 5, 6, 7, 4, 3],
       [5, 3, 5, 7, 3, 9, 4]], dtype=int16)

#                                      #Methods of Creating a Numpy array

Method 1 : NP.ARRAY([])

In [31]:
#Creating a new array
#Datatype U1 means an object/strings
np.array(['A','B','C'])

array(['A', 'B', 'C'], dtype='<U1')

In [33]:
np.array(['A','B','C',1,4,2])
#Numpy has automatically subjected the items to all become string because numpy works with a single datatype.
#Numpy does not work with variable data types

array(['A', 'B', 'C', '1', '4', '2'], dtype='<U11')

In [34]:
np.array(['A',1,'B',4,'C',2])

array(['A', '1', 'B', '4', 'C', '2'], dtype='<U11')

Method 2:A-RANGE

In [35]:
#Numpy has some functions that make it easy to create an array instead of writing them from the beginning

In [43]:
#Function 1: The A Range: creates an identical array making use of a specific set of increments
#the syntax for arange is np.srange(start,stop,steps)

In [38]:
np.arange(10) #arange creates 10 identical items starting from 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(2,14)                   #arange works similar to the range in for loop of python, starts from 2 and stops at 13

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [40]:
np.arange(2,14,4)                         #the 3rd argument gives the number of skips or increment.

array([ 2,  6, 10])

In [41]:
np.arange(2,14,3, dtype = float)       #using arange, you can convert the datatype to a float but NOT a string 

array([ 2.,  5.,  8., 11.])

Method 3:LINSPACE

In [51]:
#Linspace creates specific numbers of elements that are equally spaced
#lIN stands for linearly separable. the syntax is np.linspace(start,stop,no of items)
#By default, the linspace takes in 50 items. To change the number of items, you will have to pass the third argument
#Linspace usually returns the answer in float but can be converted to integer
np.linspace(2,20)

array([ 2.        ,  2.36734694,  2.73469388,  3.10204082,  3.46938776,
        3.83673469,  4.20408163,  4.57142857,  4.93877551,  5.30612245,
        5.67346939,  6.04081633,  6.40816327,  6.7755102 ,  7.14285714,
        7.51020408,  7.87755102,  8.24489796,  8.6122449 ,  8.97959184,
        9.34693878,  9.71428571, 10.08163265, 10.44897959, 10.81632653,
       11.18367347, 11.55102041, 11.91836735, 12.28571429, 12.65306122,
       13.02040816, 13.3877551 , 13.75510204, 14.12244898, 14.48979592,
       14.85714286, 15.2244898 , 15.59183673, 15.95918367, 16.32653061,
       16.69387755, 17.06122449, 17.42857143, 17.79591837, 18.16326531,
       18.53061224, 18.89795918, 19.26530612, 19.63265306, 20.        ])

In [45]:
np.linspace(2,20,5)      #The third argument means to return 5 items that are evenly spaced

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [46]:
#The items above are equally/evenly spaced with a difference of 4.5

In [48]:
np.linspace(2,8,4, dtype=np.int16)     #this returns the answers in integers

array([2, 4, 6, 8], dtype=int16)

In [50]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

Method 4:NUMPY.EYE()

In [53]:
#The NUMPY.EYE is another way of creating numpy arrays
#np.eye() returns a 2-Dimensional array with ones on the diagonal and zeros elsewhere
np.eye(4)   #returns 4 rows and 4 columns while ensuring that there is a diagonal across it.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
#np.eye can also take 2 arguments where it returns the number of rows and columns example
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [56]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

Method 5:NUMPY.DIAG()

In [59]:
#This numpy.diag works like the numpy.eye() but here you can specify the items you want inside the diagonal
#It will return a square matrix whose size will be = to the number of items in the array
np.diag([2,3,4])     #Here, it returns a 3 by 3 matrix with the array items in the diagonal.

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [60]:
np.diag([2,2,4,6,8])      #Here, it returns a 5 by 5 matrix with the array items in the diagonal.

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 8]])

In [62]:
#You can also alternate the position of items in the array
np.diag([2,3,4,5,7],2)
#Here, the 2nd argument of 2 increases the array to a 7 by 7 matrix and shifts each array item by 2 i.e it skips 3 items

array([[0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [63]:
np.diag([2,3,4,5,7],4)

array([[0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

Method 6: NUMPY.ZEROS()

In [1]:
#helps you to form identical number of items(zeros in this case)

In [3]:
import numpy as np

In [4]:
np.zeros(4)   #This returns an indicated number of zeros. It only takes in one argument 

array([0., 0., 0., 0.])

In [5]:
np.zeros(4,3)

TypeError: Cannot interpret '3' as a data type

Method 7:NUMPY.ONES()

In [2]:
#Returns ones into a specified number of places
import numpy as np

In [3]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

Method 8:NUMPY.FULL()

In [8]:
#It returns an item a number of times.
#The first argument is the number of times you want an item returned while the second argument is the item you want to return.
np.full(5,8)

array([8, 8, 8, 8, 8])

In [9]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Method 9: NUMPY.RANDOM()

In [4]:
np.random.rand(4)

array([0.79881568, 0.30210915, 0.84619938, 0.47370217])